apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "odf.openshift.io/v1alpha1",
          "kind": "OcsClient",
          "metadata": {
            "name": "ocsclient-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "odf.openshift.io/v1alpha1",
          "kind": "StorageClassClaim",
          "metadata": {
            "name": "storageclassclaim-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    olm.skipRange: ""
    operators.operatorframework.io/builder: operator-sdk-v1.19.0+git
    operators.operatorframework.io/operator-type: standalone
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: ocs-client-operator.v4.12.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OcsClient is the Schema for the ocsclients API
      displayName: Ocs Client
      kind: OcsClient
      name: ocsclients.odf.openshift.io
      version: v1alpha1
    - description: StorageClassClaim is the Schema for the storageclassclaims API
      displayName: Storage Class Claim
      kind: StorageClassClaim
      name: storageclassclaims.odf.openshift.io
      version: v1alpha1
  description: foo
  displayName: OpenShift Data Foundation Client Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - odf.openshift.io
          resources:
          - ocsclients
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - odf.openshift.io
          resources:
          - ocsclients/finalizers
          verbs:
          - update
        - apiGroups:
          - odf.openshift.io
          resources:
          - ocsclients/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - odf.openshift.io
          resources:
          - storageclassclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - odf.openshift.io
          resources:
          - storageclassclaims/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: ocs-client-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: ocs-client-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/ocs-dev/ocs-client-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: ocs-client-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: ocs-client-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  - data
  - storage
  links:
  - name: OCS Client Operator
    url: https://github.com/red-hat-storage/ocs-client-operator
  maintainers:
  - email: ocs-support@redhat.com
    name: Red Hat
  maturity: alpha
  provider:
    name: Red Hat
  version: 4.12.0
