# permissions for end users to view ocsclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocsclient-viewer-role
rules:
- apiGroups:
  - odf.openshift.io
  resources:
  - ocsclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - odf.openshift.io
  resources:
  - ocsclients/status
  verbs:
  - get
