apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ocs-client-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OcsClient is the Schema for the ocsclients API
      displayName: Ocs Client
      kind: OcsClient
      name: ocsclients.odf.openshift.io
      version: v1alpha1
    - description: StorageClassClaim is the Schema for the storageclassclaims API
      displayName: Storage Class Claim
      kind: StorageClassClaim
      name: storageclassclaims.odf.openshift.io
      version: v1alpha1
  description: foo
  displayName: OpenShift Data Foundation Client
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - operator
  - data
  - storage
  links:
  - name: OCS Client Operator
    url: https://github.com/red-hat-storage/ocs-client-operator
  maintainers:
  - email: ocs-support@redhat.com
    name: Red Hat
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
